[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = false
magicEnabled = true

[server]
headless = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#f59e0b"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"
